// <auto-generated />
using System;
using DuelRecords.Api.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DuelRecords.Api.Migrations.Alexandria
{
    [DbContext(typeof(AlexandriaDbContext))]
    [Migration("20260514230313_InitialAlexandria")]
    partial class InitialAlexandria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DuelRecords.Api.Models.Ygo.YgoCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Archetype")
                        .HasColumnType("text");

                    b.Property<int?>("Attack")
                        .HasColumnType("integer");

                    b.Property<string>("Attribute")
                        .HasColumnType("text");

                    b.Property<int?>("Defense")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FrameType")
                        .HasColumnType("text");

                    b.Property<string>("HumanReadableCardType")
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("LinkMarkers")
                        .HasColumnType("text");

                    b.Property<int?>("LinkValue")
                        .HasColumnType("integer");

                    b.Property<string>("LocalImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .HasColumnType("text");

                    b.Property<int?>("Scale")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YgoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YgoId")
                        .IsUnique();

                    b.ToTable("YgoCards");
                });

            modelBuilder.Entity("DuelRecords.Api.Models.Ygo.YgoCardImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Downloaded")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrlCropped")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrlSmall")
                        .HasColumnType("text");

                    b.Property<int>("ImageYgoId")
                        .HasColumnType("integer");

                    b.Property<string>("LocalCroppedImagePath")
                        .HasColumnType("text");

                    b.Property<string>("LocalImagePath")
                        .HasColumnType("text");

                    b.Property<string>("LocalSmallImagePath")
                        .HasColumnType("text");

                    b.Property<int>("YgoCardId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YgoCardId");

                    b.ToTable("YgoCardImages");
                });

            modelBuilder.Entity("DuelRecords.Api.Models.Ygo.YgoCardPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmazonPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CardMarketPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CoolStuffIncPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EbayPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TcgPlayerPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("YgoCardId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YgoCardId")
                        .IsUnique();

                    b.ToTable("YgoCardPrices");
                });

            modelBuilder.Entity("DuelRecords.Api.Models.Ygo.YgoCardSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SetPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("SetRarity")
                        .HasColumnType("text");

                    b.Property<string>("SetRarityCode")
                        .HasColumnType("text");

                    b.Property<int>("YgoCardId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YgoCardId");

                    b.ToTable("YgoCardSets");
                });

            modelBuilder.Entity("DuelRecords.Api.Models.Ygo.YgoCardImage", b =>
                {
                    b.HasOne("DuelRecords.Api.Models.Ygo.YgoCard", "YgoCard")
                        .WithMany("Images")
                        .HasForeignKey("YgoCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YgoCard");
                });

            modelBuilder.Entity("DuelRecords.Api.Models.Ygo.YgoCardPrice", b =>
                {
                    b.HasOne("DuelRecords.Api.Models.Ygo.YgoCard", "YgoCard")
                        .WithOne("Prices")
                        .HasForeignKey("DuelRecords.Api.Models.Ygo.YgoCardPrice", "YgoCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YgoCard");
                });

            modelBuilder.Entity("DuelRecords.Api.Models.Ygo.YgoCardSet", b =>
                {
                    b.HasOne("DuelRecords.Api.Models.Ygo.YgoCard", "YgoCard")
                        .WithMany("Sets")
                        .HasForeignKey("YgoCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YgoCard");
                });

            modelBuilder.Entity("DuelRecords.Api.Models.Ygo.YgoCard", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Prices");

                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
